# Generated by Django 5.2.3 on 2025-06-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('not selected', 'Not Selected')], default='not selected', max_length=20)),
                ('type', models.CharField(choices=[('given', 'Given'), ('taken', 'Taken')], max_length=10)),
                ('due_date', models.DateField()),
                ('history', models.TextField(blank=True)),
            ],
        ),
    ]
