# Generated by Django 5.0.4 on 2025-06-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='parcel name')),
                ('touch', models.FloatField(verbose_name='Parcel Touch')),
                ('Netwet', models.FloatField(verbose_name='net weight')),
                ('Gowet', models.FloatField(verbose_name='Gross weight')),
                ('PC', models.IntegerField(verbose_name='item PC')),
                ('Item', models.TextField(max_length=100)),
            ],
        ),
    ]
